### ISSUE TITLE
Work around for private repos

### ISSUE THREAD

**Issue by jlstack** [STT3851-SP15/DiscussionSTT3851#1]
Go to Tools/Shell
Then copy and paste each line individually, replacing my info with your own. 
Make sure to press enter before moving on to the next line.

git config --global user.name JLStack
git config --global user.email stackjl@appstate.edu  
git clone https://github.com/STT3851-SP15/Stack-Jordan.git

After this it will ask you for your username and password to verify who you are.
It may look like you aren't typing anything, because it hides your password when you type. 
Don't be concerned.

If it completes without any problems, you should be able to go back to R and create a new project how you would have before.

**Comment by alanarnholt** [comment]
You should make sure your user.name and user.email are in quotes "".  However, I do not believe this quite addresses the issue "error: unable to read askpass response from 'rpostback-askpass’ " several MAC users where having in class. 

If you are encountering an message to the effect: "error: unable to read askpass response from 'rpostback-askpass’ " while using a MAC,  the problem will most likely disappear if you use the credential helper.

To find out if the credential helper is already installed. In the shell, enter `git credential-osxkeychain`. You should see something like this: `Usage: git credential-osxkeychain <get|store|erase>`. 

Once you’ve confirmed you have the credential helper, enter 
`git config --global credential.helper osxkeychain`.

Further directions are available on GitHub https://help.github.com/articles/caching-your-github-password-in-git/

This fixed the problem on one machine this afternoon.  I would like to get feedback if the proposed solution works for others that are having this problem...

**Comment by alanarnholt** [comment]
For MAC users, you may need to fork a public repo, make a change using the command line tools to a file, (Say the README), then commit and push the changes back to your GitHub.  You can use something like the following once you have forked the repo and made some change.

`git add .`
`git commit -m"your message"`
`git push`

If your push is accepted and you are using the `credential.helper` you should be able to use push and pull using RStudio now.
