### ISSUE TITLE
Zotero Suggestions

### ISSUE THREAD

**Issue by alanarnholt** [STT3851-SP15/DiscussionSTT3851#3]
Go to http://library.appstate.edu/, click on the Google Scholar tab, enter your key words in the box then click search.  This should take you through the ASU library and give you access to the library data-bases without having to pay for articles.

**Comment by alanarnholt** [comment]
See the first video here https://www.youtube.com/watch?v=jlm6IYq4m3I&list=PLJBNI3mCp9g0wsSDK111qgimqVF1dwPXO for additional pointers

**Comment by mileschalmers** [comment]
Videos are really helpful, a lot of questions that would have come up are answered. Thanks

**Comment by alanarnholt** [comment]
Close
