### ISSUE TITLE
Research Proposal

### ISSUE THREAD

**Issue by erinkreiling** [STT3851-SP15/DiscussionSTT3851#5]
Hey! I don't know if anyone else is using the NESARC data set but I was wondering if you guys are changing around all the sections in the Research Proposal template. Like a lot of them already describe the data set exactly and I'm wondering if I should reword them or not.

**Comment by alanarnholt** [comment]
If class discussion yesterday did not clarify this issue please reopen.

**Comment by alanarnholt** [comment]
Close
